### ISSUE TITLE
Best way to squeeze a tensor?

### ISSUE THREAD

**Issue by dorpxam** [romeric/Fastor#107]
After reading the wiki, I don't see a equivalent to : [tensorflow squeeze](https://www.tensorflow.org/api_docs/python/tf/squeeze) in the fastor library. I see the recommandation about the different order assignation in the [Performance-tips](https://github.com/romeric/Fastor/wiki/Performance-tips) section, but nothing to automatically reshape a tensor (removing dimensions of size 1). 

Maybe a possible enhancement? 
Thank's for all Roman!

**Comment by romeric** [comment]
Hi Maxime,

Tensor `squeeze` is now implemented. Note that squeeze returns a view to the original tensor so modifiying the squeezed tensor will modify the original tensor

Examples:

~~~c++

squeeze(Tensor<double,3,1,2>)  = Tensor<double,3,2>
squeeze(Tensor<double,1>)      = Tensor<double>
squeeze(Tensor<double,1,1>)    = Tensor<double>
squeeze(Tensor<double,1,1,1>)  = Tensor<double>
squeeze(Tensor<double,1,2,1>)  = Tensor<double,2>
.
.
.
~~~

~~~c++
Tensor<double,1,2,3,1> a;
auto b = squeeze(a); 
print(type_name<decltype(b)>());
~~~ 
will give you
~~~
Fastor::TensorMap<double,2,3>
~~~

If you want a copy instead, just assign it to a tensor directly
~~~c++
Tensor<double,2,3> b = squeeze(a);
~~~

I am closing this. Feel free to open a new issue if you have one.
