### ISSUE TITLE
Broadcasting?

### ISSUE THREAD

**Issue by xloem** [romeric/Fastor#108]
I'm unsure how to broadcast assignment to across columns or rows.

The wiki states:
```
// assign a vector to all the columns of a 3D array
A(0,0,all) = vec(all);
```

But this looks like it selects the first column and first row (index 0,0): what is the actual situation here?

**Comment by romeric** [comment]
Are you comparing Fastor with MATLAB/Fortran/Julia style broadcasting?

Note that Fastor tensors are row-major (C-style or NumPy style) so the order is swapped in that:

~~~c++
Tensor<double,3> vec = {1,2,3};      // a vector
Tensor<double,2,4,3> A(0);             // 3D tensor of all zeros 
A(0,0,all) = vec(all);
print(A);
~~~
will print
~~~
[0,:,:]
[1, 2, 3]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
[1,:,:]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
[0, 0, 0]
~~~ 
Here A is a 3D tensor made up of two `4x3` matrices. 

So in `A(i,j,k)`, `i` will give you the `i`th `4x3` matrix, `j` will give you the `j`th row in that matrix and `k` will give you the `k`th column in that matrix.

So in `A(0,0,all)` you are asking Fastor to give you the first `4x3` matrix and from that matrix give you the first row and `all` the columns.

Hope that is clear.

**Comment by xloem** [comment]
Maybe I have what broadcasting is wrong.  It sounds like you are confirming that the comment I quoted from the documentation is wrong?  How do I assign the same vector to every column?

**Comment by xloem** [comment]
I see ... so by "assign a vector to all the columns" you mean that each column gets one different element of the vector.
How do we assign the same vector to every full column?  such that all rows are filled with the same value, different for each row, and all columns become the same new vector?

**Comment by romeric** [comment]
Right I see that the documentation is incorrect. I will correct that. We don't have much documentation for Fastor at the moment. 

What you are asking is essentially tiling `numpy.tile, numpy.repeat` or MATLAB's `repmat` feature to broadcast a vector to all elements of a tensor. This feature is unfortunately not implemented yet, but there is a high request rate for it. I will implement this as soon as I get some time. 

Something like
~~~c++
Tensor<double,1,3> vec = {1,2,3};
Tensor<double,3,3> A = repeat<1,3>(vec); // repeat 3 times, column-wise (1 for column-wise and 3 for number of repitition)
~~~

~~~
[1, 1, 1]
[2, 2, 2]
[3, 3, 3]
~~~

For the time being however, unfortantely you will have to implement this with for loops

**Comment by xloem** [comment]
Thanks, that's very clarifying.  Maybe I can try to stub an interface out with a naive implementation if I am bored, and submit a PR.

**Comment by romeric** [comment]
You are welcome to submit a PR if you wish

**Comment by romeric** [comment]
Also see #103
