### ISSUE TITLE
Einsum fails with TensorMap using -std=c++20 (g++, clang)

### ISSUE THREAD

**Issue by matthiasneuner** [romeric/Fastor#114]
Following MWE fails with activated `-std=c++20` (both on g++ (GCC) 10.1.0 and clang version 10.0.0 ), but works perfectly without the flag:
```
#include "Fastor/Fastor.h"

int main ()
{

    enum {i,j};
    double data[] = {1,2,3,4};
    Fastor::TensorMap<double, 2, 2>  A ( (data) ) ;                                                                                    
    auto result =    Fastor::einsum < Fastor::Index<i,j>, Fastor::Index<i,j>>  (A, A); 

    return 0;
}
```

Thank you in advance :-) !

**Comment by romeric** [comment]
Thanks for reporting the issue. This is now fixed 201cd70. Please download the latest copy of Fastor.
If there is an issue, please open a new one. Closing.
