### ISSUE TITLE
Writing to views of TensorMap fails

### ISSUE THREAD

**Issue by matthiasneuner** [romeric/Fastor#116]
Hello,
this MWE does not compile for me on g++ 10:
```
    using namespace Fastor;

    double data[4] = { };

    auto A = TensorMap<double, 2, 2>(data);

    Tensor<double, 2, 1> b;
    b = { {1},{1}};

    A(fseq<0, 2>(), fseq<1, 2>()) = b;
```
It seems that writing to blocks of TensorMap fails, while it works for standard Tensors as intended.
Thank you in advance :-)

**Comment by romeric** [comment]
Thanks for reporting the issue. It is now fixed 6d1ecc3. The fix is available if you download the latest copy of Fastor.
