### ISSUE TITLE
eye() on a TensorMap results in a SEGFAULT

### ISSUE THREAD

**Issue by matthiasneuner** [romeric/Fastor#119]
Hello Roman,

I have a very strange issue.
Basically, I try to set `.eye()` on a `TensorMap`, which results in a SEGFAULT:

```
BftClassicalRotationIntegrator3D::BftClassicalRotationIntegrator3D( double* stateVars )
    : Rn( stateVars ), dRn_dX( stateVars + 9 )
{
}

void BftClassicalRotationIntegrator3D::initialize()
{
    /* Eigen::Map<Eigen::Matrix3d> ( Rn.data() ) = Eigen::Matrix3d::Identity(); */  // <<--- works perfectly
    Rn.eye(); // <-- SEGFAULT

    std::cout << Rn << std::endl;
}
```

Valgrind delivers me following output:

```
==521499== 
==521499== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==521499==  General Protection Fault
==521499==    at 0x1F48C7F5: _mm_store_pd (emmintrin.h:166)
==521499==    by 0x1F48C7F5: store (simd_vector_double.h:655)
==521499==    by 0x1F48C7F5: zeros (TensorMethods.h:36)
==521499==    by 0x1F48C7F5: eye (TensorMethods.h:60)
==521499==    by 0x1F48C7F5: BftClassicalRotationIntegrator3D::initialize() (bftClassicalFiniteRotationIntegrator.cpp:63)
```

Setting the preallocated memory using `Eigen` to `Identity` works perfectly.
Of course, the preallocated memory is ensured, so I can exclude any problems here.
Do you have any clue what causes this kind of behavior?
Thank you in advance!

**Comment by romeric** [comment]
That is a memory alignment issue. Fixed here 4f3e4e1. Let me know otherwise.
There are also some changes coming in the next minor release that will improve working with unaligned data even more.
