### ISSUE TITLE
Variable size tensors?

### ISSUE THREAD

**Issue by matejbadin** [romeric/Fastor#122]
This is more less just a question - Is there a plan to implement variable sized tensors, hence tensors which dimension is unknown at compile time or take as dimensions input from variables?

**Comment by romeric** [comment]
Short anwswer is No. I have some unfinished work from a while ago with dynamic tensors, however to make that reach the level of maturity that Fastor has reached would require some significant work. Even if that happened it would be a sister project to Fastor and most probably would not be pushed here. 

Thanks,
Roman
