### ISSUE TITLE
CMake script for library installation?

### ISSUE THREAD

**Issue by mablanchard** [romeric/Fastor#126]
Woud be nice for Fastor to provide a rather simple toplevel `CMakeList.txt` that would allow installing the library to a system directory (possibly respecting the [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) `CMAKE_INSTALL_INCLUDEDIR` standard variable?). This would simplify integration of the library in complex software stacks where build is automated. Tests building could also be included in that CMake script (possibly using the no-standard-but-widly-use `BUILD_TESTING` variable?)

**Comment by mablanchard** [comment]
I could work on a patch if the project is willing to accept such a script.

**Comment by romeric** [comment]
Yes, I agree. I have been meaning to do this. By all means, please feel free to submit a PR if you have one.
