### ISSUE TITLE
Multiple defintion of `Fastor::useless::extract_type(std::basic_string_view<char, std::char_traits<char> >&, std::basic_string_view<char, std::char_traits<char> >)'

### ISSUE THREAD

**Issue by matthiasneuner** [romeric/Fastor#130]
Hello,

in Debian 11 (gcc10, binutils 2.35.1) and Centos 8 (gcc9-2,  binutils 2.30-79.el8) I get linking errors due to multiple definitions of 
`Fastor::useless::extract_type(std::basic_string_view<char, std::char_traits<char> >&, std::basic_string_view<char, std::char_traits<char> >)` 
in Fastor/utils/types.h .
I do not really understand why those clashes arise, but commenting out the `#if __cplusplus >= 201703L` block solves the problem. (Alternatively passing` -Wl,--allow-multiple-defintions` also helps, but cannot be considered a real solution)
What causes this issue?

Thank you and best regards, Matthias

**Comment by romeric** [comment]
Does it help if you declare the function `inline` [here]?(https://github.com/romeric/Fastor/blob/8f29c6f2ac914b3936c9d5a9a3695638d123f69a/Fastor/util/types.h#L10) 

Also its definition a few lines down perhaps.

**Comment by matthiasneuner** [comment]
This helps perfectly for both operating systems! Thank you for the quick response ! If you want, I can create a PR tomorrow?
