### ISSUE TITLE
Can't construct tensor, Tensor<double, 32, 256, 256>

### ISSUE THREAD

**Issue by soleil0-0** [romeric/Fastor#134]
Can't use `Tensor<double, 32, 256, 256>`, I got `Process finished with exit code -1073741571 (0xC00000FD)`.

If I decrease the last number, less than or equal to 31 is ok. (Tensor<double, 32, 256, 31>)

**Comment by Bbllaaddee** [comment]
Hey!

Might it be related to the amount of memory your computer have?

The tensor you're trying to create is 32\*256\*256 numbers, which is exactly 16 GB in size (assuming `sizeof(double) = 8` byte).
Whereas the least tensor that you have problems with is 32*256\***32** double-precision numbers, which is exactly 2 GB in size.

So, when you are trying to use less than 2 GBs it works. How much RAM does you computer have?

**Comment by jcarpent** [comment]
> The tensor you're trying to create is 32*256*256 numbers, which is exactly 16 GB in size

I guess you meant MB ;)

**Comment by Bbllaaddee** [comment]
> > The tensor you're trying to create is 32_256_256 numbers, which is exactly 16 GB in size
> 
> I guess you meant MB ;)

OH GOD..
I forgot the last division by 1024 xD 
Forget it please)

But the strange integer-number pattern is still there xD

**Comment by romeric** [comment]
Fastor tensors are created on the stack and not the heap as they are all static arrays. Computers stack limit is mainly 2MB. 

If you want those big tensors than I'm afraid Fastor is not designed for that. 

If you really want to this see other related issues #59 #26.
