### ISSUE TITLE
Micro-feature: scalar-type tensor to scalar type

### ISSUE THREAD

**Issue by Bbllaaddee** [romeric/Fastor#138]
Hello!

I wonder if there's any way of transforming a ```Tensor<double>``` to ```double```, for example.
I found the following way:
```c++
Tensor<double> a = 5;
double b = *a.data();
```
, but it seems a little verbose.

Probably implement
```c++
template<typename T>
T Tensor<T>::operator T() {} // pseudo-syntax
```
of some sort for conversion?

Cheers!

**Comment by romeric** [comment]
This is already implemented as 

~~~c++
Tensor<double> a = 3;
double b = a.toscalar();
~~~
