### ISSUE TITLE
Prefix for Fastor definitions

### ISSUE THREAD

**Issue by dimbert** [romeric/Fastor#16]
Could I suggest to prefix Fastor definition with `FASTOR_` to avoid conflicts with other libs? For example `Zero` or `One` defined in `commons.h` are pretty common. Moreover some of them are not used.

Thanks for this nice work !

**Comment by romeric** [comment]
Thanks for your input. Ideally all definitions should have `FASTOR_` prefix. I would look into this very shortly.

**Comment by romeric** [comment]
The issue is now fixed in 0769141. Many thanks for reporting.
