### ISSUE TITLE
Pivoting speed

### ISSUE THREAD

**Issue by rfabbri** [romeric/Fastor#172]
Hi,
 
`std::abs` used in pivoting when `std::norm` should be faster?
Eigen uses `std::norm`. The code is run hundreds of millions of times in some applications.

Thanks.

**Comment by romeric** [comment]
[dbf4419](https://github.com/romeric/Fastor/commit/dbf4419864a15501bb363e73b477fb22f4461dcd) fixes the issue. Thanks for reporting.
