### ISSUE TITLE
Crash with large tensor.

### ISSUE THREAD

**Issue by DakeQQ** [romeric/Fastor#175]
Dear,

My all Android phones crash when allocating a large tensor, such as Fastor::Tensor<float, 2048, 2048>. I'm sure the RAM is sufficient. Additionally, I found that the crash seems related to the cumulative allocation size in the same project, not just a single large allocation. Any ideas on how to solve this?

**Comment by romeric** [comment]
Fastor does not use heap memory. The description of Fastor in says that it is a stack-allocated tensor library and hence and such large sizes cannot be allocated. Fastor is not designed for big dynamic arrays and is not a substitute for them.
