### ISSUE TITLE
Support for complex numbers

### ISSUE THREAD

**Issue by ebatz** [romeric/Fastor#19]
Is there a way to make Fastor support `std::complex<double>` (or similar) as a data type?
It seems like `vector_setter` will have to be specialized to add support for complex numbers.

**Comment by romeric** [comment]
Without the SIMD support (SSE/AVX ...) std::complex should work fine. I will look in to this shortly to see what the issue is. Should not be too difficult to fix (but you never know).

**Comment by romeric** [comment]
The recent commits 010ae54 and ec82d56 fix the issue. You should now be able to use `std::complex<T>` with `T=[double/float]` as a data type for tensors. Sorry for the belated fix.

**Comment by romeric** [comment]
See also #78 for request for native SIMD support for complex types

**Comment by romeric** [comment]
SIMD support for complex floats/doubles has now been added from SSE2 all the way to AVX512 including a new scalar fall-back class and fully tested for all available configurations [latest commit d5a16b4].
