### ISSUE TITLE
Wiki or Documentation

### ISSUE THREAD

**Issue by ClmnsRck** [romeric/Fastor#20]
As i am currently trying to understand and follow this framework, it would be really helpful for you to release a extensive documentation, listing all current features, things to expect, things to steer clear from and just related stuff. If i have missed this document somewhere, pardon me.

**Comment by romeric** [comment]
Thanks for opening an issue on this. Documentation is a critical requirement of the library. Due to other commitments unfortunately I am not being able to dedicate enough time to work on it. I will reopen the issue to serve as a reminder for us to work on this in the near future.

**Comment by romeric** [comment]
I have started working on the wiki [here](https://github.com/romeric/Fastor/wiki/Getting-Started). Will put more stuff in to it incrementally.
