### ISSUE TITLE
benchmark_backend: ./benchmark_matmul.exe: runtime-error

### ISSUE THREAD

**Issue by ClmnsRck** [romeric/Fastor#24]
Running your backend_benchmarks, causes this error. 
```
Running customised matmul kernels for 3D numerical quadrature [Benchmarks SIMD vectorisation]
Matrices size (M, K, N) 3 4 3 Speed-up over scalar code [elapsed time] 2.32717 [saved CPU cycles] 9 
free(): invalid next size (fast)
Makefile:45: recipe for target 'run' failed
make: *** [run] Aborted (core dumped)
```

**Comment by romeric** [comment]
What compiler are you using to compile the code and what architecture/OS?

**Comment by ClmnsRck** [comment]
Ubuntu 18.04.2 64-bit(dont know if this is even possbile on 32-bit) on a Intel CPU and g++-7.3.0

**Comment by romeric** [comment]
I will have a look at this shortly. This bug seems vaguely familiar and I reckon I know where it is coming from.

**Comment by romeric** [comment]
8f4c6ae should have fixed this. Please report otherwise. Closing.

**Comment by ClmnsRck** [comment]
It works now, thanks
