### ISSUE TITLE
[bug] einsum with Matrix-Vector causes segmentation-fault

### ISSUE THREAD

**Issue by ClmnsRck** [romeric/Fastor#28]
When compiling this code:
```
Tensor<T, I> a;
Tensor<T, J,I> b;

Tensor<T, J> c = einsum<Index<a,b>, Index<b>>(b,a);
```
I get a segmentation-fault. Is this not allowed? or am i overlooking something essential here?

**Comment by romeric** [comment]
For the record, this is not a valid code. You are mixing up sizes, tensors and indices which is not allowed. What you would want to do is

~~~c++
enum {I,J}; // indices
constexpr size_t size_I = 10;  // size
constexpr size_t size_J = 4;  // size
Tensor<T, size_I> a; // vector of size 10
Tensor<T, size_I, size_I> b; // // matrix of size 4x10

Tensor<T, size_J> c = einsum<Index<I,J>, Index<J>>(b,a);
~~~

Despite this the actual error that you are reporting still persisted and commit 899c6c0 has fixed it.
