### ISSUE TITLE
Outer-Product using einsum nearly crashes system during compilation

### ISSUE THREAD

**Issue by ClmnsRck** [romeric/Fastor#29]
When trying to compile the later code, gcc gets caught in an infinite loop and nearly crahses the system(mine atleast) when trying to compile the second outer-product of two vectors(I = 100, h= 50, O =10):
```
template<typename T, long I, long h, long O>
void fastorFF(cTensor<T> &In, cTensor<T> &tar){
    T learnR = 0.05;

    Fastor::Tensor<T, I, 1> inputs;
    Fastor::Tensor<T, h, I> w_ih; w_ih.random();
    Fastor::Tensor<T, O, h> w_ho; w_ho.random();
    Fastor::Tensor<T, O, 1> target;
    Fastor::Tensor<T, h, 1> b_h; b_h.random();
    Fastor::Tensor<T, O, 1> b_o; b_o.random();
    for(int i = 0; i < I; ++i){
        inputs(i, 0) = In.get2({i});
    }
    for(int i = 0; i < O; ++i){
        target(i, 0) = tar.get2({i});
    }
    {
        Fastor::Tensor<T, h, 1> hidden = Fastor::einsum<Fastor::Index<a,b>, Fastor::Index<b,c>>(w_ih, inputs);
        hidden += b_h;
        hidden = (1)/(1 + exp((-1)*hidden));

        Fastor::Tensor<T, O, 1> output = Fastor::einsum<Fastor::Index<a,b>, Fastor::Index<b,c>>(w_ho, hidden);
        output += b_o;
        hidden = (1)/(1 + exp((-1)*output));

        Fastor::Tensor<T, O, 1> o_error = target - output;

        Fastor::Tensor<T, O, 1> gradient = learnR * o_error * (output * (1 - output));
        b_o += gradient;
===>w_ho += Fastor::einsum<Fastor::Index<a, b>, Fastor::Index<c, d>>(gradient, hidden);

        Fastor::Tensor<T, h, 1> h_error = Fastor::einsum<Fastor::Index<b,a>, Fastor::Index<b,c>>(w_ho, o_error);

        Fastor::Tensor<T, h, 1> h_gradient = learnR * h_error * (hidden * (1 - hidden));
        b_h += h_gradient;
===>w_ih += Fastor::einsum<Fastor::Index<a,b>, Fastor::Index<c, d>>(h_gradient, inputs);
    }
}
```
(every lower-case letter inside of Fastor::Index<> has been globally defined as an enum in ascending order)

**Comment by ClmnsRck** [comment]
I've tried it again and only had my fastor code defined. When doing this, my system actually kills `g++` to prevent further problems

**Comment by romeric** [comment]
What are your compilation flags? Are you using the `-DCONTRACT_OPT=2` flag by any chance?

**Comment by ClmnsRck** [comment]
Yes, does that screw with the system?

**Comment by romeric** [comment]
Yes, it does. Unfortunately this is rather a compiler limitation. `-DCONTRACT_OPT=2` does a lot of compile time arithmetics using template meta programming. Unfortunately meta (compile time) analysis is recursive in nature and not iterative hence, once the recursion depth is too deep the compiler hangs and consumes almost your entire memory. 

For this reason `-DCONTRACT_OPT=1` exists which should be used for most problems of practical interest. Let me know if this solves the problem so I can close the issue.

**Comment by ClmnsRck** [comment]
It did, thank you a lot. I will go ahead and close this issue.
