### ISSUE TITLE
problem when use einsum

### ISSUE THREAD

**Issue by XDongiang** [romeric/Fastor#33]
when i use einsum example :
```c++
enum{i,j,k};
Tensor<double, 2, 2> a  = {{1, 2}, {3, 4}};
Tensor<double, 2>    w  = {1, 1};
auto e3 = einsum<Index<i, j>, Index <i> >(a, w);
//it ruturn 
[4.000]
[0.000]
````
why?

**Comment by romeric** [comment]
This is a bug that occurs under scalar (non-SIMD) mode. If you compile with `-march=native` you won't see this.

Nevertheless, it is a bug and thanks for reporting. I have fixed it now in 70838d2.
