### ISSUE TITLE
when i use * to multiply two tensor i meet a bug

### ISSUE THREAD

**Issue by XDongiang** [romeric/Fastor#38]
```c++
auto MMM(Tensor<double, 4>& a)
{
    enum { i, j, k, l, m, n, o, p };
    Tensor<double, 4> Kp1 = {1, 1, 1, 8};
    auto              x   = einsum<Index<i>, Index<j>>(Kp1, Kp1);
    auto              result =
        einsum<Index<i, j>, Index<k, l>>(x, x);
        // einsum<Index<i, j>, Index<k, l>, Index<m, n>, Index<o, p>>(x, x, x, x);
    // auto aaa = result* result;
    Tensor<double,4,4> KK = {{1,2,3,4},{1,2,3,4},{1,2,3,4},{1,2,3,4}};
    // print(KK);
    auto aaa = KK * KK ;

    return aaa;
}
int main()
{
    Tensor<double, 4>    Psi = {40, 0, 0, 3686};
    auto mmm = MMM(Psi);
    std::cout << __LINE__ << std::endl
    print(mmm);
}

//it return 
135
[  0,   0,   0,   0]
[  0,   0,   0,   0]
[  0, inf, inf, inf]
[inf, inf,   0,   0]

//but when i change it with 
auto MMM(Tensor<double, 4>& a)
{
    enum { i, j, k, l, m, n, o, p };
    Tensor<double, 4> Kp1 = {1, 1, 1, 8};
    auto              x   = einsum<Index<i>, Index<j>>(Kp1, Kp1);
    auto              result =
        einsum<Index<i, j>, Index<k, l>>(x, x);
        // einsum<Index<i, j>, Index<k, l>, Index<m, n>, Index<o, p>>(x, x, x, x);
    // auto aaa = result* result;
    Tensor<double,4,4> KK = {{1,2,3,4},{1,2,3,4},{1,2,3,4},{1,2,3,4}};
     print(KK);
    auto aaa = KK * KK ;
    return aaa;
}

// it  return 
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
135
[ 1,  4,  9, 16]
[ 1,  4,  9, 16]
[ 1,  4,  9, 16]
[ 1,  4,  9, 16]

```

**Comment by romeric** [comment]
That makes sense. 

You are using the keyword `auto` so `aaa` is not a tensor, it is rather a an expression. Whenever you use `+`, `-`, `*` and `/` or use mathematical functions on the tensors such as `sqrt`, `exp`, `log`, `sin` etc the result does not get computed when you use the keyword `auto`. You have to manually force it to compute the tensor by giving the tensor type 

For example in function `MMM` if you print the type of `aaa` like this:

~~~c++
print(type_name<decltype(aaa)>());
~~~

you will see

~~~c++
Fastor::BinaryMulOp<Fastor::Tensor<double, 4ul, 4ul>, Fastor::Tensor<double, 4ul, 4ul>, 2ul>
~~~

So always use the actual tensor type when you are multiplying, adding, subtracting ... your tensors. Also don't use `auto` for return types. So your function `MMM` should look like this

~~~c++
Tensor<double,4,4> MMM(Tensor<double, 4>& a)
{
    enum { i, j, k, l, m, n, o, p };
    Tensor<double, 4> Kp1 = {1, 1, 1, 8};
    auto x   = einsum<Index<i>, Index<j>>(Kp1, Kp1);
    auto result = einsum<Index<i, j>, Index<k, l>>(x, x);

    Tensor<double,4,4> KK = {{1,2,3,4},{1,2,3,4},{1,2,3,4},{1,2,3,4}};
    Tensor<double,4,4> aaa = KK * KK ;

    return aaa;
}

int main()
{
    Tensor<double, 4> Psi = {40, 0, 0, 3686};
    auto mmm = MMM(Psi);
    print(mmm);
}
~~~ 

Note that `einsum` always returns a tensor so using `auto` for `einsum` is fine.

**Comment by XDongiang** [comment]
> That makes sense.
> 
> You are using the keyword `auto` so `aaa` is not a tensor, it is rather an expression. Whenever you use `+`, `-`, `*` and `/` or use mathematical functions on the tensors such as `sqrt`, `exp`, `log`, `sin` etc the result does not get computed specially when you use the keyword `auto`. You have to manually force it to compute the tensor by giving the actual tensor type instead of `auto`.
> 
> For example, in function `MMM` if you print the type of `aaa` like this:
> 
> ```c++
> print(type_name<decltype(aaa)>());
> ```
> 
> you will see that it is not a tensor, but a complex expression between two tensors
> 
> ```c++
> Fastor::BinaryMulOp<Fastor::Tensor<double, 4ul, 4ul>, Fastor::Tensor<double, 4ul, 4ul>, 2ul>
> ```
> 
> So always use the actual tensor type when you are multiplying, adding, subtracting ... your tensors. Also don't use `auto` for return types of functions. So your function `MMM` should look like this
> 
> ```c++
> Tensor<double,4,4> MMM(Tensor<double, 4>& a)
> {
>     enum { i, j, k, l, m, n, o, p };
>     Tensor<double, 4> Kp1 = {1, 1, 1, 8};
>     auto x   = einsum<Index<i>, Index<j>>(Kp1, Kp1);
>     auto result = einsum<Index<i, j>, Index<k, l>>(x, x);
> 
>     Tensor<double,4,4> KK = {{1,2,3,4},{1,2,3,4},{1,2,3,4},{1,2,3,4}};
>     Tensor<double,4,4> aaa = KK * KK ;
> 
>     return aaa;
> }
> 
> int main()
> {
>     Tensor<double, 4> Psi = {40, 0, 0, 3686};
>     auto mmm = MMM(Psi);
>     print(mmm);
> }
> ```
> 
> Note that `einsum` always returns a tensor so using `auto` for `einsum` is fine.

thank you for your help. i will fix my code

**Comment by romeric** [comment]
The underlying bug here pertains to issue #95
