### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by AuroraDysis** [romeric/Fastor#5]
It looks an awesome work.
Do you know [mshadow](https://github.com/dmlc/mshadow)?
It support CPU/GPU together through
```
Tensor<cpu, 2> ts1;
Tensor<gpu, 2> ts1;
```
[This document](http://computing.ornl.gov/workshops/SMC15/docs/posters/smc15_tensor_contractions.pdf) also may be helpful.

**Comment by romeric** [comment]
Thanks for the suggestion. I am aware of mshadow and it certainly looks like a promising project.
