### ISSUE TITLE
Possibility to use Fastor on godbolt compiler explorer?

### ISSUE THREAD

**Issue by romeric** [romeric/Fastor#53]

**Comment by FabienPean** [comment]
It is now available following merge of https://github.com/compiler-explorer/compiler-explorer/pull/2076 and https://github.com/compiler-explorer/infra/pull/364. See the running example [https://godbolt.org/z/n6f9qY](https://godbolt.org/z/n6f9qY)

**Comment by romeric** [comment]
Awesome stuff @FabienPean.
Thanks for the related godbolt PR.
