### ISSUE TITLE
Syntax confusion.

### ISSUE THREAD

**Issue by ninnghazad** [romeric/Fastor#61]
Trying to divide every element of each row of a 2d tensor by a single element from a 1d tensor. 
In numpy i would do `m / d[:,None]`.

```
Tensor<float,3,2> m{{2,4},{8,16},{32,64}};
Tensor<float,3> d{2,4,8};
auto r { m / d };  // nope

Tensor<float,3,1> d{{2},{4},{8}}; // won't even compile

[insert 27 more ways i tried to do this]
???
```

**Comment by romeric** [comment]
You have to use the equivalent of numpy's `:` syntax which is `all`

~~~c++
        Tensor<float,3,2> result;
        result(all,0) = m(all,0) / d;
        result(all,1) = m(all,1) / d;
~~~

Will work. Note that `[:,None]` promotes your tensor to 2D in numpy which is not supported currently in Fastor, but I will soon add `hstack` feature so you can do this

~~~c++
        Tensor<float,3,2> result = m / hstack<2>(d,d);
~~~

Let me know if it helps

**Comment by romeric** [comment]
The other issue you reported regarding compilation is fixed in fecda90. The fix is available if you download a new copy of Fastor.

So now 

~~~c++
Tensor<float,3,1> d{{2},{4},{8}};
~~~

prints

~~~
[2]
[4]
[8]
~~~

while 

~~~c++
Tensor<float,1,3> d{{2,4,8}};
~~~

prints 

~~~
[2, 4, 8]
~~~

**Comment by romeric** [comment]
Thanks for reporting. Feel free to ask

**Comment by ninnghazad** [comment]
Thank you. The fix works and the example too. Looking forward to that hstack feature.
