### ISSUE TITLE
Implicit conversion of Tensor<T> to scalar

### ISSUE THREAD

**Issue by romeric** [romeric/Fastor#7]
Requested by Sebastian Moeckel:

Is there any plan to implement some implicit casting of `Tensor<T>` to `T`? i.e. writing
~~~c++
T C = einsum<Index<I>,Index<I>>(A,B);
~~~
would be possible?

**Comment by romeric** [comment]
Depending on what you want to achieve this is already possible. For example, the above example could be written as

~~~c++
T C = inner(A,B);
~~~ 

For generic tensor algorithms one can explicitly cast the result of a function returning `Tensor<T>` to scalar by

~~~c++
T C = method_returning_scalar_tensor(A,B,...).toscalar();
~~~

**Comment by semoe** [comment]
Thank you - I was not aware of the toscalar() functionality.
