### ISSUE TITLE
Best way to get min or max element, is tensor finite ?

### ISSUE THREAD

**Issue by dorpxam** [romeric/Fastor#90]
Thank you for this excellent library, very useful and powerful. I'm working on a portage of old armadillo based project to fastor and need a little help (maybe a enhancement request) from you.

1) I need to get the `max` absolute value of a tensor. The element-wise `abs` expression is already implemented, but I can't see equivalent for getting `min` or `max` in the same elegant way, something like:
```
    Tensor<double,2,3,4> a;
    double max_abs_value = max(abs(a));
```
2) Fastor implement some compile time boolean operations like `isuniform`, how can I get runtime equivalent of `isfinite` over a tensor ?
```
    Tensor<double,2,3,4> a;
    bool ok = isfinite(a);
```
Sorry if it's not pertinent or if it's not the best place to ask help, let me known.
Thank you very much.
Max

**Comment by romeric** [comment]
Thank you for submitting this issue. Yes, element-wise `max/min` and `isfinite` is not yet implemented. I will add these as soon as possible. Hopefully will be available later today or early tomorrow.

**Comment by romeric** [comment]
`min` and `max` functions have now been implemented. You need the latest commit/clone of Fastor for this. So now you can do

~~~c++
Tensor<T,....> a;
T max_value = max(a);
T max_abs_value = std::max(abs(a));
~~~

The `isfinite` function will be available soon

**Comment by dorpxam** [comment]
Wonderfull, you make my day !

**Comment by dorpxam** [comment]
Roman, if you want to see why your work is so usefull, take a look at this issue : https://github.com/HSU-ANT/ACME.jl/issues/28

Your library is incredible !!!

**Comment by romeric** [comment]
That is absolutely awesome Maxime 👍! I am glad that you are finding a solid scientific application that you can use Fastor for. 

People typically come and explore Fastor and when they realise that it is only for fixed sized arrays they leave it at that. So I am happy that your usecase is suited for this kind heavy compile time computations that Fastor is designed for.

On other news, I have now implemented `isnan`, `isinf` and `isfinite` for Fastor expressions with proper unittests. However note, similar to numpy and matlab these operations are element-wise. 

~~~c++
Tensor<T,....> a;
Tensor<bool,....> result_array = isfinite(a);
~~~

If you want to know that all of the elements are finite you can do

~~~c++
bool ok = all_of(isfinite(a));
~~~
or use `any_of` or `none_of` depending on the use case. You need the latest clone of Fastor for this.

Please ask if you have any questions.
