### ISSUE TITLE
Intel MKL cblas GEMV vs Fastor matrix-vector product (divergence)

### ISSUE THREAD

**Issue by dorpxam** [romeric/Fastor#92]
Just a quick question about the precision divergence between Intel MKL and Fastor in matrix-vector product ?

Test code compiled with Visual Studio 2019 v16.5.5 / Intel MKL 2020.0.166 :
```
inline void fastor_vs_mkl()
{
    Tensor<double, 14, 7> A
    {
        { -1.93781838657913e-06, -3.27309170041656e-06,                   0.0,     -1.00635004669251,     0.999999486757164,  0.0, 0.0 },
        {                   0.0,                   0.0,                   0.0,                   0.0,                   1.0,  0.0, 0.0 },
        {  1.93781838657913e-10,  3.27309170041656e-10,                   0.0,  0.000110635004669251,  5.13242835593115e-11,  0.0, 0.0 },
        { -1.89658820814127e-10, -3.20345145147152e-10,                   0.0,   -0.0001106348956674, -9.97722191580435e-05,  0.0, 0.0 },
        {     -1.06298622040787,  3.27309170041656e-06,                   0.0,      1.00005123086988,  5.13242835593115e-07,  0.0, 0.0 },
        {  1.02902828693888e-06, -3.16853020369463e-12,                   0.0, -0.000203346812787895, -4.96846888279879e-13,  0.0, 1.0 },
        {      1.06298622040787, -3.27309170041656e-06,                   0.0,     -1.00005123086988, -5.13242835593115e-07, -1.0, 0.0 },
        {                   0.0,                   0.0,                   0.0,                   0.0,                   0.0,  0.0, 1.0 },
        {                   0.0,                   0.0,                   0.0,                   0.0,                   0.0,  1.0, 0.0 },
        {                   0.0,                   0.0,                   0.0,                   0.0,                   0.0,  0.0, 1.0 },
        {  1.93781838657913e-06,       1.0000032730917,     -1.01011337868481,  5.12308698843822e-05,  5.13242835593115e-07,  0.0, 0.0 },
        {  1.93781838657913e-06,       1.0000032730917,                   0.0,  5.12308698843822e-05,  5.13242835593115e-07,  0.0, 0.0 },
        {                   0.0,                   0.0,  0.000111011337868481,                   0.0,                   0.0,  0.0, 0.0 },
        {  3.61182967707817e-06, -4.03105576627626e-05, -0.000111011337868481, -1.37000546071824e-09, -1.37250351013743e-11,  0.0, 0.0 },
    };

    Tensor<double, 7> x
    {
           -0.010348922599724,
        -0.000970905869296285,
         6.29508830237331e-10,
         -5.9442706607832e-05,
            -8.99999859753792,
         -0.00405450106433774,
        -3.89453215139354e-10,
    };

    Tensor<double, 14> y
    {
             8.99992959241464,
                          0.0,
         7.04075853554555e-09,
        -0.000897956411287056,
         7.04075853554555e-05,
        -6.81583594922125e-11,
        -7.04075853554555e-05,
                          0.0,
                          0.0,
                          0.0,
         7.04075853554555e-05,
            -8.99992959241464,
                          0.0,
         -1.8828252698158e-09,
    };

    auto z = A % x + y;

    std::cout << z << std::endl;

    cblas_dgemv(CBLAS_ORDER::CblasRowMajor, 
				CBLAS_TRANSPOSE::CblasNoTrans,
				MKL_INT(14), 
				MKL_INT(7),
				1.0,
				A.data(),
				MKL_INT(7),
				x.data(),
				MKL_INT(1),
				1.0,
				y.data(),
				MKL_INT(1));

    std::cout << y << std::endl;
}
```
Result:

**FASTOR**
```
[-4.54253570758567e-06] ***
[    -8.99999859753792]
[ 7.27127379263199e-14]
[-7.99852805516421e-14] ***
[   0.0110071015903558]
[  9.8501396074225e-10]
[ -0.00695260052601804]
[-3.89453215139354e-10]
[ -0.00405450106433774]
[-3.89453215139354e-10]
[ -0.00090514438211466]
[    -9.00090514374623]
[ 6.98826174446686e-14]
[-7.71610226268768e-14] ***
```
**INTEL MKL**
```
[-4.54253570936203e-06] ***
[    -8.99999859753792]
[ 7.27127379263199e-14]
[-7.99853889718594e-14] ***
[   0.0110071015903558]
[  9.8501396074225e-10]
[ -0.00695260052601804]
[-3.89453215139354e-10]
[ -0.00405450106433774]
[-3.89453215139354e-10]
[ -0.00090514438211466]
[    -9.00090514374623]
[ 6.98826174446686e-14]
[-7.71610226322535e-14] ***            
``` 
Divergence of precision in rows 1, 4 & 14 (***), but I can't explain why. Any idea ?

PS: Notice that **Fastor** is clearly **Faster** than MKL for such tensors sizes ! Great !

**Comment by romeric** [comment]
How are you compiling your code? Are you activating SIMD or vector instructions `/arch:[sse,avx,avx512]` in Visual Studio? 

I think this difference is expected given that MKL and Fastor might use different SIMD/vector instructions or different variants of the vector instructions. You are calling the MKL shared library which by default uses the highest register-width (128/256/512 bits) available in your machine, while Fastor will dispatch the call to whatever vector instruction you supply to the compiler. If you are supplying none of the above no vector instructions would be used by Fastor and the difference in values would be very likely.

**Comment by dorpxam** [comment]
Compiler : `Visual Studio 2019 v16.5.5` 
Library : `Intel MKL 2020.0.166`

I'm running the code on a old Dell Workstation from 2007 with `Intel Xeon CPU (E5410 @ 2.33GHz)`.

`Intel MKL` is linked statically with `MTd`/ `MT`.

The static library are different for the `ia32`/ `intel64` :
`ia32 -> mkl_blas95.lib`
`intel64 -> mkl_blas95_lp64.lib` 

`Release` mode is set with `/O2 /Ob2 /Oi`

For information, VS2019 seem to declare the `_M_IX86_FP` intrinsinc preprocessor with or without /arch:SSE2 setted in the build properties. I've look at the Fastor's `common.h` for this assertion.

OK, so i've running the code in `debug` and `release`, `x86` and `x64`.

**Fastor** (`x86 `same result in `debug` and `release`)
```
[-4.54253570758567e-06] ***
[    -8.99999859753792]
[ 7.27127379263199e-14]
[-7.99852805516421e-14] ***
[   0.0110071015903558]
[  9.8501396074225e-10]
[ -0.00695260052601804]
[-3.89453215139354e-10]
[ -0.00405450106433774]
[-3.89453215139354e-10]
[ -0.00090514438211466]
[    -9.00090514374623]
[ 6.98826174446686e-14]
[-7.71610226268768e-14] ***
```
**Intel MKL** (`x86 `same result in `debug` and `release`)
```
[-4.54253570936203e-06] ***
[    -8.99999859753792]
[ 7.27127379263199e-14]
[-7.99853889718594e-14] ***
[   0.0110071015903558]
[  9.8501396074225e-10]
[ -0.00695260052601804]
[-3.89453215139354e-10]
[ -0.00405450106433774]
[-3.89453215139354e-10]
[ -0.00090514438211466]
[    -9.00090514374623]
[ 6.98826174446686e-14]
[-7.71610226322535e-14] ***
```
**Fastor** (`x64 `same result in `debug` and `release`)
```
[-4.54253570758567e-06]
[    -8.99999859753792]
[ 7.27127379263199e-14]
[-7.99852805516421e-14] ***
[   0.0110071015903558]
[  9.8501396074225e-10]
[ -0.00695260052601804]
[-3.89453215139354e-10]
[ -0.00405450106433774]
[-3.89453215139354e-10]
[ -0.00090514438211466]
[    -9.00090514374623]
[ 6.98826174446686e-14]
[-7.71610226268768e-14] ***
```
**Intel MKL** (`x64 `same result in `debug` and `release`)
```
[-4.54253570758567e-06]
[    -8.99999859753792]
[ 7.27127379263199e-14]
[-7.99853889718594e-14] ***
[   0.0110071015903558]
[  9.8501396074225e-10]
[ -0.00695260052601804]
[-3.89453215139354e-10]
[ -0.00405450106433774]
[-3.89453215139354e-10]
[ -0.00090514438211466]
[    -9.00090514374623]
[ 6.98826174446686e-14]
[-7.71610226326671e-14] ***
```
The result is constant with `Fastor` for the 4 different builds
where the result change with `Intel MKL`, the first row become same in `x64` build. Strangely, the precision error do not occur in the same place:
```
[-7.9985|2805516421e-14]
[-7.9985|3889718594e-14]

[-7.71610226|268768e-14]
[-7.71610226|326671e-14]
```
Thank you very much for your help and thank you so much for the quick update (min/max & isfinite)

**Comment by romeric** [comment]
Wow. Thanks for the detailed analysis. I am actually amazed that Fastor even runs on 32 bit configuration on Windows on an old machine such as yours. We don't run unit tests on Windows normally (only from release to release). 

Yes almost all compilers these days define at least `SSE2` by default on most X86 architectures. Fastor is specifically tuned to take advantage of this fact in that we try backport/rewrite some newer SSE3/4 instruction using SSE2 to take advantage of default compiler flags, so you almost never get a non-SIMD Fastor code. It seems like your computer also supports `SSE4.2`. Fastor will run slightly faster under `SSE4.2` although I don't think that will affect your usecase i.e. `dgemv`.

Regarding the original issue, the variation in the results that you are seeing here is actually coming MKL and not from Fastor as you have observed. MKL is known to have numerical reproducibility issues. See [Introduction to Conditional Numerical Reproducibility (CNR)](https://software.intel.com/content/www/us/en/develop/articles/introduction-to-the-conditional-numerical-reproducibility-cnr.html) for instance or search through Intel's forum you will find a lot of similar issues that people have posted. In particular it seems that if you set 

~~~c++
mkl_cbwr_set(MKL_CBWR_COMPATIBLE)
~~~

MKL will give you a SSE2 only code. So perhaps worth trying. I am closing this issue for now, but feel free to open a new one if you think there is still an issue here with Fastor.
